name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 BINARY_NAME=bin/regan-linux-amd64 make build
    - name: Build Mac OS Intel
      run: GOOS=darwin GOARCH=amd64 BINARY_NAME=bin/regan-mac-intel make build
    - name: Build Mac OS Apple Silicon
      run: GOOS=darwin GOARCH=arm64 BINARY_NAME=bin/regan-mac-arm make build
    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 BINARY_NAME=bin/regan.exe make build

    - name: Upload binaries
      uses: actions/upload-artifact@v3.1.0
      with:
        name: binaries
        path: bin/regan*
        if-no-files-found: error
