on:
  release:
    types: [created]
name: Release
jobs:
  generate:
    name: Attach release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 BINARY_NAME=bin/regan-linux-amd64 make build
      - name: Build Mac OS Intel
        run: GOOS=darwin GOARCH=amd64 BINARY_NAME=bin/regan-mac-intel make build
      - name: Build Mac OS Apple Silicon
        run: GOOS=darwin GOARCH=arm64 BINARY_NAME=bin/regan-mac-arm make build
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 BINARY_NAME=bin/regan.exe make build

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/regan*'
